baseURL = "https://maastrichtu-cds.github.io/BEACH-semantic-map/"
theme = "hugo-book"
title = "BEACH Knowledge Representation"
enableGitInfo = true
disablePathToLower = true

[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1

[menu]
[[menu.after]]
name = "About BEACH"
url = "https://clinicaldatascience.nl"
weight = 10

[[menu.after]]
name = "BEACH GitHub"
url = "https://github.com/MaastrichtU-CDS/BEACH-semantic-map"
weight = 20

[params]
BookTheme = 'auto'
BookToC = false
BookFavicon = 'favicon.ico'
BookSection = 'BEACH-20K-NSCLC-data-semantic-map'
BookDateFormat = 'January 2, 2006'

# Used for 'Last Modified' and 'Edit this page' links.
BookRepo = 'https://github.com/MaastrichtU-CDS/BEACH-semantic-map'